ApiExecutionsDefault:
  handler: index.executions
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ExecutionsTable:
      function: Ref
      value: ExecutionsTableDynamoDB
  apiGateway:
    #default paths
    - path: executions
      method: get
      cors: true
      api: backend
    - path: executions/{arn}
      method: get
      cors: true
      api: backend

ApiExecutionStatusDefault:
  handler: index.executionStatus
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
  apiGateway:
    #default paths
    - path: executions/status/{arn}
      method: get
      cors: true
      api: backend

ApiWorkflowsDefault:
  handler: index.workflows
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    bucket: '{{parent.system_bucket}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
  apiGateway:
    #default paths
    - path: workflows
      method: get
      cors: true
      api: backend
    - path: workflows/{name}
      method: get
      cors: true
      api: backend

ApiRulesDefault:
  handler: index.rules
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  envs:
    bucket: '{{parent.system_bucket}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    RulesTable:
      function: Ref
      value: RulesTableDynamoDB
    invoke:
      function: "Ref"
      value: ScheduleSFLambdaFunction
    invokeArn:
      function: "Ref"
      value: ScheduleSFLambdaFunction
    kinesisConsumer:
      function: "Ref"
      value: kinesisConsumerLambdaFunction
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
  source: 'node_modules/@cumulus/api/dist/'
  apiGateway:
    #default paths
    - path: rules
      method: get
      cors: true
      api: backend
    - path: rules/{name}
      method: get
      cors: true
      api: backend
    - path: rules
      method: post
      cors: true
      api: backend
    - path: rules/{name}
      method: put
      cors: true
      api: backend
    - path: rules/{name}
      method: delete
      cors: true
      api: backend

ApiLogsDefault:
  handler: index.logs
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiRole: true
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
  apiGateway:
    #default paths
    - path: stats/logs
      method: get
      cors: true
      api: backend
    - path: logs
      method: get
      cors: true
      api: backend
    - path: logs/{executionName}
      method: get
      cors: true
      api: backend

ApiTokenDefault:
  handler: index.token
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiRole: true
  urs: true
  envs:
    EARTHDATA_BASE_URL: '{{parent.urs_url}}'
    EARTHDATA_CLIENT_ID: '{{EARTHDATA_CLIENT_ID}}'
    EARTHDATA_CLIENT_PASSWORD: '{{EARTHDATA_CLIENT_PASSWORD}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    OAUTH_PROVIDER: '{{parent.oauth.provider}}'
  apiGateway:
    #default paths
    - api: backend
      path: token
      method: get
      cors: true
