ApiExecutionsV1:
  handler: index.executions
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
    ExecutionsTable:
      function: Ref
      value: ExecutionsTableDynamoDB
  apiGateway:
    #v1 paths
    - path: v1/executions
      method: get
      cors: true
      api: backend
    - path: v1/executions/{arn}
      method: get
      cors: true
      api: backend

ApiExecutionStatusV1:
  handler: index.executionStatus
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
  apiGateway:
    #v1 paths
    - path: v1/executions/status/{arn}
      method: get
      cors: true
      api: backend

ApiRulesV1:
  handler: index.rules
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  apiRole: true
  envs:
    bucket: '{{parent.system_bucket}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    RulesTable:
      function: Ref
      value: RulesTableDynamoDB
    invoke:
      function: "Ref"
      value: ScheduleSFLambdaFunction
    invokeArn:
      function: "Ref"
      value: ScheduleSFLambdaFunction
    kinesisConsumer:
      function: "Ref"
      value: kinesisConsumerLambdaFunction
    ES_HOST:
      function: Ref
      value: ElasticSearchDomain
  source: 'node_modules/@cumulus/api/dist/'
  apiGateway:
    #v1 paths
    - path: v1/rules
      method: get
      cors: true
      api: backend
    - path: v1/rules/{name}
      method: get
      cors: true
      api: backend
    - path: v1/rules
      method: post
      cors: true
      api: backend
    - path: v1/rules/{name}
      method: put
      cors: true
      api: backend
    - path: v1/rules/{name}
      method: delete
      cors: true
      api: backend

ApiTokenV1:
  handler: index.token
  timeout: 20
  memory: '{{parent.api_lambda_memory}}'
  source: 'node_modules/@cumulus/api/dist/'
  apiRole: true
  urs: true
  envs:
    EARTHDATA_BASE_URL: '{{parent.urs_url}}'
    EARTHDATA_CLIENT_ID: '{{EARTHDATA_CLIENT_ID}}'
    EARTHDATA_CLIENT_PASSWORD: '{{EARTHDATA_CLIENT_PASSWORD}}'
    UsersTable:
      function: Ref
      value: UsersTableDynamoDB
    OAUTH_PROVIDER: '{{parent.oauth.provider}}'
  apiGateway:
    #v1 paths
    - api: backend
      path: v1/token
      method: get
      cors: true
