RulesTable:
  read: 5
  write: 1
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: name
      type: S
      schema: HASH

ExecutionsTable:
  read: 5
  write: 10
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: arn
      type: S
      schema: HASH

UsersTable:
  read: 5
  write: 1
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: userName
      type: S
      schema: HASH
