default:
  stackName: simple-cumulus
  stackNameNoDash: simpleCumulus

  apiStage: dev

  vpc:
    vpcId: '{{VPC_ID}}'
    subnets:
      - '{{AWS_SUBNET}}'

  ecs:
    instanceType: t2.small

  system_bucket: '{{buckets.internal.name}}'

  buckets:
    internal:
      name: '{{stackName}}-internal-bucket'
      type: internal

  iams:
    ecsRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-ecs'
    lambdaApiGatewayRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-lambda-api-gateway'
    lambdaProcessingRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-lambda-processing'
    stepRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-steprole'
    instanceProfile: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:instance-profile/{{stackName}}-ecs'
    distributionRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-distribution-api-lambda'
    scalingRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-scaling-role'

  # Override ES as none so no Elasticsearch cluster is created
  es:
